services:
  frontend-app:
    build: .
    container_name: andres_portfolio
    ports:
        - "3000:3000"
    volumes:
        - .:/app:z
        - /app/node_modules
        - /app/.next
    environment:
        - NODE_EV=development
        - WATCHPACK_POLLING=true